Empezamos importando librerias

In [89]:
import numpy as np

In [90]:
def descompLU_recursive(A):
    #get dimensions of A
    n = A.shape[0]

    u_11 = A[0,0]
    if (u_11 == 0): # whe cannot pivot anymore, the A matrix cannot be descomposed
        return (None, None)

    if (n == 1):
        return (np.array([[1]]), np.array([[u_11]]))
    

    u_12 = A[0, 1:]

    l_21 = A[1:, 0] / u_11

    recursive_A_matrix_to_solve = A[1:, 1:] - l_21.reshape(n - 1,1) * u_12

    l_22, u_22 = descompLU_recursive(recursive_A_matrix_to_solve)
    if (l_22 is None or u_22 is None): # returns canonical and original A
        return (None, None)
    

    l_top_row = np.array([1] + [0] * (n - 1))
    #create a new matrix using the l_22 matrix with dimensions of (n - 1, n - 1) and the l_21 matrix with dimensions of (n - 1, 1)
    l = np.hstack((np.expand_dims(l_21, axis=1), l_22))
    l = np.vstack((l_top_row, l))

    #create a new matrix using the l matrix with dimensions of (n - 1, n) and the l_top_row matrix with dimensions of (1, n)
    u_left_row = np.array([u_11] + [0] * (n - 1))
    #create a new matrix using the u_22 matrix with dimensions of (n - 1, n - 1) and the u_12 matrix with dimensions of (1, n - 1)
    u = np.vstack((u_12, u_22))
    #create a new matrix using the u matrix with dimensions of (n, n - 1) and the u_left_row matrix with dimensions of (n, 1)
    u = np.hstack((np.expand_dims(u_left_row, axis=1), u))

    return (l, u)

def descompLU(A):
    l, u = descompLU_recursive(A)
    if (l is None or u is None): # returns canonical and original A
        return (np.eye(A.shape[0]), A)
    return (l, u)


In [91]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])

l, u = descompLU(matrix)

print(l)
print(u)

[[1. 0. 0.]
 [4. 1. 0.]
 [7. 2. 1.]]
[[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0.  1.]]
